# Generated by Django 5.0.1 on 2024-02-16 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0038_resumefile_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('min_salery', models.CharField(default='', max_length=255)),
                ('max_salery', models.CharField(default='', max_length=255)),
                ('salery_type', models.CharField(default='', max_length=255)),
                ('education', models.CharField(default='', max_length=255)),
                ('experience', models.CharField(default='', max_length=255)),
                ('job_type', models.CharField(default='', max_length=255)),
                ('vaсancies', models.CharField(default='', max_length=255)),
                ('expiration_date', models.CharField(default='', max_length=255)),
                ('job_level', models.CharField(default='', max_length=255)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employer')),
            ],
        ),
    ]
