# Generated by Django 5.0.1 on 2024-02-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_vacancy_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
