# Generated by Django 5.0.1 on 2024-02-29 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_employer_banner_alter_employer_logo'),
        ('vacancy', '0003_vacancy_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='applications', to='user.candidate'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='user.employer'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancy.vacancy')),
            ],
            options={
                'unique_together': {('vacancy', 'candidate')},
            },
        ),
    ]
