# Generated by Django 5.0.1 on 2024-02-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_alter_vacancy_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
