# Generated by Django 5.0.1 on 2024-03-02 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_remove_candidate_user_id_candidate_user'),
        ('vacancy', '0006_alter_vacancy_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancys', to='user.employer'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='user.candidate'),
        ),
    ]
