# Generated by Django 5.0.1 on 2024-03-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_rename_user_id_employer_user_and_more'),
        ('vacancy', '0010_remove_vacancy_vacancies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='applied_jobs', to='user.candidate'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
