# Generated by Django 5.0.1 on 2024-01-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customuser_verification_code_emailverificator'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificator',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
