# Generated by Django 5.0.1 on 2024-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_emailverificator_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificator',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
