# Generated by Django 5.0.1 on 2024-01-29 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_verificator_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('headlinee', models.CharField(default='0', max_length=255)),
                ('experiences', models.CharField(default='0', max_length=999)),
                ('educations', models.CharField(default='0', max_length=999)),
                ('website', models.CharField(default='0', max_length=999)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('map_location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('company_name', models.CharField(default='0', max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
                ('organization_type', models.CharField(default='0', max_length=255)),
                ('industry', models.CharField(default='0', max_length=255)),
                ('team_size', models.CharField(default='0', max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('year_of_establishment', models.DateField(blank=True, null=True)),
                ('company_vision', models.TextField(blank=True, null=True)),
                ('map_location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employer')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate')),
            ],
        ),
    ]
