# Generated by Django 5.0.1 on 2024-01-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_candidate_candidatesociallink_employer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='industry',
            new_name='industry_types',
        ),
        migrations.AlterField(
            model_name='employer',
            name='about',
            field=models.TextField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_vision',
            field=models.TextField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='map_location',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.CharField(blank=True, default='0', null=True),
        ),
    ]
