# Generated by Django 5.0.1 on 2024-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_industry_employer_industry_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='candidate/profile_pics'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='media/banners'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo'),
        ),
        migrations.AlterField(
            model_name='resumefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='candidate/resumes'),
        ),
    ]
