# Generated by Django 5.0.1 on 2024-02-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_candidate_full_name_alter_candidate_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='headlinee',
            new_name='headline',
        ),
    ]
