# Generated by Django 5.0.1 on 2024-02-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_headlinee_candidate_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employersociallink',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employersociallink',
            name='social_network',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
