# Generated by Django 5.0.1 on 2024-02-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_employer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='five_job_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rejection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='shortlist',
            field=models.BooleanField(default=False),
        ),
    ]
