# Generated by Django 5.0.1 on 2024-02-03 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_candidate_profile_privasy_candidate_resume_privasy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='profile_save',
            new_name='profile_saved',
        ),
    ]
