# Generated by Django 5.0.1 on 2024-02-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_rename_profile_save_candidate_profile_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='profile_privasy',
            new_name='profile_privacy',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_privasy',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_privacy',
            field=models.BooleanField(default=False),
        ),
    ]
