# Generated by Django 5.0.1 on 2024-02-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_rename_profile_privasy_candidate_profile_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_vision',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry_types',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='map_location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='organization_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='employer',
            name='team_size',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.CharField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='year_of_establishment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
