# Generated by Django 5.0.1 on 2024-02-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_employer_about_alter_employer_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employersociallink',
            name='frontend_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
