# Generated by Django 5.0.1 on 2024-02-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_employersociallink_frontend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='logo',
        ),
    ]
