# Generated by Django 5.0.1 on 2024-02-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_employer_banner_employer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='./banners'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='./logo'),
        ),
    ]
