# Generated by Django 5.0.1 on 2024-02-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_candidate_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_of_birth',
            field=models.CharField(blank=True, null=True),
        ),
    ]
