# Generated by Django 5.0.1 on 2024-02-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_candidate_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='email',
            new_name='candidate_email',
        ),
    ]
