# Generated by Django 5.0.1 on 2024-02-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_rename_email_employer_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='candidate_email',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
