# Generated by Django 5.0.1 on 2024-02-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_employer_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='candidate_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
