# Generated by Django 5.0.1 on 2024-02-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_employer_candidate_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='candidate_email',
            new_name='candidate_mail',
        ),
    ]
