# Generated by Django 5.0.1 on 2024-02-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_rename_candidate_email_employer_candidate_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='candidate_mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
