# Generated by Django 5.0.1 on 2024-02-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_rename_candidate_mail_employer_email_candidate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employersociallink',
            name='employer',
        ),
        migrations.AddField(
            model_name='candidate',
            name='links',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='employer',
            name='links',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='CandidateSocialLink',
        ),
        migrations.DeleteModel(
            name='EmployerSocialLink',
        ),
    ]
