# Generated by Django 5.0.1 on 2024-02-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_remove_employersociallink_employer_candidate_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='educations',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='experiences',
            field=models.CharField(default='', max_length=999),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='headline',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='', max_length=999),
        ),
    ]
