# Generated by Django 5.0.1 on 2024-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_candidate_educations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='size',
            field=models.CharField(default='', max_length=255),
        ),
    ]
