# Generated by Django 5.0.1 on 2024-02-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_resumefile_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_icon.png', null=True, upload_to='candidate/profile_pics'),
        ),
    ]
