# Generated by Django 5.0.1 on 2024-03-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_alter_employer_banner_alter_employer_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='user',
            new_name='user_id',
        ),
    ]
