# Generated by Django 5.0.1 on 2024-03-02 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_rename_user_candidate_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_query_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
