# Generated by Django 5.0.1 on 2024-03-03 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_remove_candidate_user_candidate_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='employer', related_query_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
